### Get all users
GET http://localhost:3000/contacts
Content-Type: application/json

###

### Get a user by ID
GET http://localhost:3000/contacts/67db5f15bd7bbae0ac6ac3ef
Content-Type: application/json

###

### Create a new user
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Oliver",
  "lastName": "Garcia",
  "email": "oliver.garcia@example.com",
  "favoriteColor": "Orange",
  "birthday": "1993-07-12"
}

###

### Update a user

PUT http://localhost:3000/contacts/67db5f15bd7bbae0ac6ac3ef
Content-Type: application/json

{
    "firstName": "Liam Updated",
    "lastName": "Smith",
    "email": "liam.smith.updated@example.com",
    "favoriteColor": "Green",
    "birthday": "1985-06-24"
  }

###

### Delete a user
DELETE http://localhost:3000/contacts/67db6194e98b51154af48d01